name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: windows
            title: Windows
            runs-on: windows-latest
          - target: macos
            title: Mac
            runs-on: macos-14
          - target: linux
            title: Linux
            runs-on: ubuntu-latest

    name: build${{ matrix.title }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Restore Previous Cache
        id: cache-build-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/debug/${{ matrix.target }}/haxe/
            export/debug/${{ matrix.target }}/obj/
          key: cache-${{ matrix.target }}-debug

      - name: Set Cache Status | In Windows
        id: cache-status-windows
        if: matrix.target == 'windows'
        run: echo CACHE_HIT=${{ steps.cache-build-restore.outputs.cache-hit }} | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: powershell

      - name: Set Cache Status | In Unix
        id: cache-status-unix
        if: matrix.target != 'windows'
        run: echo "CACHE_HIT=${{ steps.cache-build-restore.outputs.cache-hit }}" >> $GITHUB_ENV

      - name: Install dependencies
        if: matrix.target == 'linux'
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib

      - name: Installing Libraries
        run: haxe --interp -cp ./actions/libs-installer -D analyzer-optimize -main Main

      - name: Setup hxcpp | In Windows
        if: env.CACHE_HIT != 'true' && matrix.target == 'windows'
        run: haxelib git hxcpp https://github.com/MAJigsaw77/hxcpp.git patch-1 --quiet && haxelib run lime rebuild hxcpp -verbose
        shell: cmd

      - name: Setup hxcpp | In Unix
        if: env.CACHE_HIT != 'true' && matrix.target != 'windows'
        run: haxelib git hxcpp https://github.com/MAJigsaw77/hxcpp.git patch-1 --quiet && haxelib run lime rebuild hxcpp -verbose

      - name: Rebuild extension-webm
        run: haxelib run lime rebuild extension-webm ${{ matrix.target }}

      - name: Fix extension-webm naming for ARM64
        if: matrix.target == 'macos'
        run: |
          mkdir -p .haxelib/extension-webm/git/ndll/MacArm64
          if [ -f ".haxelib/extension-webm/git/ndll/MacArm64/extension-webm-64.ndll" ]; then
            cp .haxelib/extension-webm/git/ndll/MacArm64/extension-webm-64.ndll .haxelib/extension-webm/git/ndll/MacArm64/extension-webm.ndll
          elif [ -f ".haxelib/extension-webm/git/ndll/Mac64/extension-webm.ndll" ]; then
            cp .haxelib/extension-webm/git/ndll/Mac64/extension-webm.ndll .haxelib/extension-webm/git/ndll/MacArm64/extension-webm.ndll
          fi

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Compile
        run: haxelib run lime build ${{ matrix.target }} -debug

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: await require('./actions/cache/clear-cache.js')({github, context}, 'cache-${{ matrix.target }}-debug');

      - name: Save Current Cache
        uses: actions/cache@main
        with:
          key: cache-${{ matrix.target }}-debug
          path: |
            .haxelib/
            export/debug/${{ matrix.target }}/haxe/
            export/debug/${{ matrix.target }}/obj/
          restore-keys: |
            cache-${{ matrix.target }}-debug

      - name: Tar files
        if: matrix.target == 'macos'
        run: tar -zcvf build.tar.gz export/debug/macos/bin

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}Build
          path: export/debug/${{ matrix.target }}/bin

  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Restore Previous Cache
        id: cache-build-restore
        uses: actions/cache/restore@main
        with:
          path: |
            .haxelib/
            export/debug/android/haxe/
            export/debug/android/obj/
          key: cache-android-debug

      - name: Set Cache Status
        id: cache-status
        run: echo "CACHE_HIT=${{ steps.cache-build-restore.outputs.cache-hit }}" >> $GITHUB_ENV

      - name: Installing Libraries
        run: haxe --interp -cp ./actions/libs-installer -D analyzer-optimize -main Main

      - name: Setup hxcpp
        if: env.CACHE_HIT != 'true'
        run: haxelib git hxcpp https://github.com/MAJigsaw77/hxcpp.git patch-1 --quiet && haxelib run lime rebuild hxcpp -verbose

      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime setup android
          haxelib run lime build android -debug

      - name: Clear Previous Cache
        uses: actions/github-script@main
        with:
          script: await require('./actions/cache/clear-cache.js')({github, context}, 'cache-android-debug');

      - name: Save Current Cache
        uses: actions/cache@main
        with:
          key: cache-android-debug
          path: |
            .haxelib/
            export/debug/android/haxe/
            export/debug/android/obj/
          restore-keys: |
            cache-android-debug

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild
          path: export/debug/android/bin/app/build/outputs/apk/debug
